### ISSUE TITLE
Solder and collect the components needed to add movement functionality.

### ISSUE THREAD

**Issue by makijurowski** [WatPi/WatPi#3]

**Comment by ayuspark** [comment]
Soldering iron was very hard to please, so was the soldering process. Our soldering iron was more than 10 years old, and we were not sure if the tip was oxidized -- the tip didn't seem to be hot to melt the solder instantly, hence the it was hard to place the solder blob precisely on the pin with the perfect amount of solder blob. 

### Issues:
- imperfect solder blobs, not sure if connectivity was affected
- no I2C address detected after connecting to the Pi(`i2cdetect -y 1`, result: all dashes)

### Solved:
- Tested the connectivity among the solder blobs, all responded positive
- **Used proper charger to the Pi.** The previous no detection of I2C addresses may be due to low voltage power cord(was using USB cable connected to the laptop to power to the Pi, hence not enough power to run the chip on the HAT(?))

*Success!*
https://photos.app.goo.gl/hjn3k9vkgmAf4kdj2
